//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlks_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.SuDungDichVus = new HashSet<SuDungDichVu>();
        }
    
        public int Id { get; set; }
        public int KhachHangId { get; set; }
        public int PhongId { get; set; }
        public System.DateTime NgayCheckin { get; set; }
        public System.DateTime NgayCheckout { get; set; }
        public string TrangThai { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVu> SuDungDichVus { get; set; }
    }
}
