//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlks_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int Id { get; set; }
        public string SoPhong { get; set; }
        public int LoaiPhongId { get; set; }
        public decimal GiaMoiDem { get; set; }
        public int SucChua { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayCheckin { get; set; }
        public Nullable<System.DateTime> NgayCheckout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
