//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlks_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int Id { get; set; }
        public int DatPhongId { get; set; }
        public int DichVuId { get; set; }
        public int SoLuong { get; set; }
        public decimal ThanhTien { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
